# Sol Lewitt 122

In [2]:
# Boring but neccesary inputs
import numpy as np
from itertools import combinations 

In [3]:
def create_cube(edge_list):
    '''

    function that given a list of indexes creates a cube representation
    3x4 matrix with 1's (edges) on those indexes

    input:
            edge_list: List of indexes where an edge exists
    output:
            cube: 3x4 matrix representing the cube with edges specified in edge_list
            
    '''
    cube = np.zeros(12)
    for index in edge_list:
        cube[index] = 1
    cube = cube.reshape((3,4))

    return cube

In [4]:
def cubes_with_n_edges(n_edges):
    '''
    
    This function returns a list of all possible cubes that have n_edges 
    (losts of repetitions though)
    
    input:
            n_edges: Number of existing edges
    output:
            cube_list: List of all possible cubes with n_edges
    '''
    
    comb = combinations(list(range(12)), n_edges)
    cube_list = []
    for item in comb:
        cube_list.append(create_cube(item))
        
    return cube_list

## Lets try to characterize the cube with a 3 by 4 numpy matrix

In [5]:
# How to use the create_cube function
cube = create_cube([2,4])
print(cube)

[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
for n_edges in range(3):
    cube_list = cubes_with_n_edges(n_edges)
    print ('Number of edges: ', n_edges, 'Number of cubes: ', len(cube_list), '\n')
    for item in cube_list:
        print(item, '\n')

Number of edges:  0 Number of cubes:  1 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

Number of edges:  1 Number of cubes:  12 

[[1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]] 

[[0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]] 

[[0. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]] 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]] 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]] 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]] 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 1.]] 

Number of edges:  2 Number of cubes:  66 

[[1. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[1. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[1. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]] 

[[1. 0. 

In [ ]:
'''

So this works with a lot of duplication

To do list:

* Function to generate all rigid transformations

* Function to transfor cube into graph to check for connectedness

* Function to to check if structure is 3D

* Optional Function to generate an actual picture of the cube possibly using povray

'''
