# Sol Lewitt 122

In [1]:
# Boring but neccesary inputs
import numpy as np
from itertools import combinations 

In [2]:
def create_cube(edge_list):
    '''

    function that given a list of indexes creates a cube representation
    3x4 matrix with 1's (edges) on those indexes

    input:
            edge_list: List of indexes where an edge exists
    output:
            cube: 3x4 matrix representing the cube with edges specified in edge_list
            
    '''
    cube = np.zeros(12,dtype=int)
    for index in edge_list:
        cube[index] = 1
    cube = cube.reshape((3,4))

    return cube

In [3]:
def cubes_with_n_edges(n_edges):
    '''
    
    This function returns a list of all possible cubes that have n_edges 
    (losts of repetitions though)
    
    input:
            n_edges: Number of existing edges
    output:
            cube_list: List of all possible cubes with n_edges
    '''
    
    comb = combinations(list(range(12)), n_edges)
    cube_list = []
    for item in comb:
        cube_list.append(create_cube(item))
        
    return cube_list

## Create a dictionary with information about all possible cube structures

In [4]:
cubes_info = {}
for n_edges in range(13):
    cubes_info[n_edges]={}
    cube_list = cubes_with_n_edges(n_edges)
    cubes_info[n_edges]['full list'] = cube_list


In [5]:
len(cubes_info)

13

In [6]:
print(cubes_info.keys())

dict_keys([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])


In [7]:
print(cubes_info[2])

{'full list': [array([[1, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]]), array([[1, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]]), array([[1, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0]]), array([[1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0]]), array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0]]), array([[1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0]]), array([[1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]]), array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0]]), array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0]]), array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0]]), array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 1]]), array([[0, 1, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]]), array([[0, 1, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0]]), array([[0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0]]), array([[0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0]]), array([[0,

In [8]:
    print ('Number of edges: ', n_edges,',   Number of cubes: ', len(cube_list), '\n')
    for item in cube_list:
        print(item, '\n')

Number of edges:  12 ,   Number of cubes:  1 

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] 



In [ ]:
'''

So this works with a lot of duplication

To do list:

* Function to generate all rigid transformations

* Function to transfor cube into graph to check for connectedness

* Function to to check if structure is 3D

* Optional Function to generate an actual picture of the cube possibly using povray

'''
