# Sol Lewitt 122

In [1]:
# Boring but neccesary inputs
import numpy as np
from itertools import combinations 
import networkx as nx

In [2]:
def create_cube(edge_list):
    '''

    function that given a list of indexes creates a cube representation
    3x4 matrix with 1's (edges) on those indexes

    input:
            edge_list: List of indexes where an edge exists (edges labelled from 1 to 12)
    output:
            cube: 3x4 matrix representing the cube with edges specified in edge_list
            
    '''
    cube = np.zeros(12,dtype=int)
    for index in edge_list:
        cube[index] = 1
    cube = cube.reshape((3,4))

    return cube

In [3]:
def cubes_with_n_edges(n_edges):
    '''
    
    This function returns a list of all possible cubes that have n_edges 
    (losts of repetitions though)
    
    input:
            n_edges: Number of existing edges
    output:
            cube_list: List of all possible cubes with n_edges
    '''
    
    comb = combinations(list(range(12)), n_edges)
    cube_list = []
    for item in comb:
        cube_list.append(create_cube(item))
        
    return cube_list

## Create a dictionary with information about all possible cube structures

In [4]:
cubes_info = {}
for n_edges in range(13):
    cubes_info[n_edges]={}
    cube_list = cubes_with_n_edges(n_edges)
    cubes_info[n_edges]['full list'] = cube_list


In [5]:
def matrix_to_graph(cube_matrix):
    edge_vertex = { 1: ( 1, 2),
                    2: ( 2, 3),
                    3: ( 3, 4),
                    4: ( 4, 1),
                    5: ( 1, 5),
                    6: ( 2, 6),
                    7: ( 3, 7),
                    8: ( 4, 8),
                    9: ( 5, 6),
                   10: ( 6, 7),
                   11: ( 7, 8),
                   12: ( 5, 8),      
                    }
    cube_graph  =  nx.Graph()
    cube_graph.add_nodes_from(list(range(1,9)))
    cube_vector = cube_matrix.reshape(12)
    
    edges_to_add = []
    for item in range(12):
        if cube_vector[item]==1:
            edges_to_add.append(edge_vertex[item+1])
    cube_graph.add_edges_from(edges_to_add)
            
    return cube_graph

In [6]:
test_cube=create_cube([2,3])
print(test_cube)

[[0 0 1 1]
 [0 0 0 0]
 [0 0 0 0]]


In [7]:
test_cube_graph = matrix_to_graph(test_cube)
print(nx.info(test_cube_graph))
print('nodes: ', test_cube_graph.nodes)
print('edges: ', test_cube_graph.edges)

Name: 
Type: Graph
Number of nodes: 8
Number of edges: 2
Average degree:   0.5000
nodes:  [1, 2, 3, 4, 5, 6, 7, 8]
edges:  [(1, 4), (3, 4)]


In [8]:
'''
Loop over the graphs and eliminate not connected ones

nx.is_connected(G)
'''

'\nLoop over the graphs and eliminate not connected ones\n\nnx.is_connected(G)\n'

In [9]:
'''

So this works with a lot of duplication

To do list:

* Function to generate all rigid transformations

* Function to transfor cube into graph to check for connectedness

* Function to to check if structure is 3D

* Optional Function to generate an actual picture of the cube possibly using povray

'''


'\n\nSo this works with a lot of duplication\n\nTo do list:\n\n* Function to generate all rigid transformations\n\n* Function to transfor cube into graph to check for connectedness\n\n* Function to to check if structure is 3D\n\n* Optional Function to generate an actual picture of the cube possibly using povray\n\n'