# Sol Lewitt 122

In [14]:
# Boring but neccesary inputs
import numpy as np
from itertools import combinations 

## Lets try to characterize the cube with a 3 by 4 numpy matrix

In [15]:
# Cube with no sticks
cube = np.zeros((3,4))
print (cube)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
cube = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(cube)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [17]:
cube.reshape((3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
# Ok lets make a function that given a list of indexes creates a cube with 1's (edges) on those indexes
def create_cube(edge_list):
    cube = np.zeros(12)
    for index in edge_list:
        cube[index]=1
    cube=cube.reshape((3,4))
    return cube

In [19]:
cube = create_cube([2,4])

In [28]:
# Let's see if we can list all the cubes with two edges
comb = combinations(list(range(12)), 2) 

In [25]:
for item in comb:
    print (item)

(0, 1)
(0, 2)
(0, 3)
(0, 4)
(0, 5)
(0, 6)
(0, 7)
(0, 8)
(0, 9)
(0, 10)
(0, 11)
(1, 2)
(1, 3)
(1, 4)
(1, 5)
(1, 6)
(1, 7)
(1, 8)
(1, 9)
(1, 10)
(1, 11)
(2, 3)
(2, 4)
(2, 5)
(2, 6)
(2, 7)
(2, 8)
(2, 9)
(2, 10)
(2, 11)
(3, 4)
(3, 5)
(3, 6)
(3, 7)
(3, 8)
(3, 9)
(3, 10)
(3, 11)
(4, 5)
(4, 6)
(4, 7)
(4, 8)
(4, 9)
(4, 10)
(4, 11)
(5, 6)
(5, 7)
(5, 8)
(5, 9)
(5, 10)
(5, 11)
(6, 7)
(6, 8)
(6, 9)
(6, 10)
(6, 11)
(7, 8)
(7, 9)
(7, 10)
(7, 11)
(8, 9)
(8, 10)
(8, 11)
(9, 10)
(9, 11)
(10, 11)


In [29]:
len(list(comb))

66

In [33]:
def cubes_with_n_edges(n_edges):
    comb = combinations(list(range(12)), n_edges) 
    n_cubes = len(list(comb))
    return n_cubes

In [40]:
for n_edges in range(13):
    print(cubes_with_n_edges(n_edges))

1
12
66
220
495
792
924
792
495
220
66
12
1


In [ ]:
'''

So this works with a lot of duplication

To do list:

* Function to generate all rigid transformations

* Function to transfor cube into graph to check for connectedness

* Function to to check if cube is 3D

* Optional Function to generate an actual picture of the cube possibly using povray

'''
