# Sol Lewitt 122

In [1]:
# Boring but neccesary inputs
import numpy as np

## Lets try to characterize the cube with a 3 by 4 numpy matrix

In [3]:
# Cube with no sticks
cube = np.zeros((3,4))
print (cube)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
cube=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(cube)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [5]:
cube.reshape((3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
# Ok lets make a function that given a list of indexes creates a cube with 1's (edges) on those indexes
def create_cube(edge_list):
    cube = np.zeros(12)
    for index in edge_list:
        cube[index]=1
    cube=cube.reshape((3,4))
    return cube

In [13]:
cube = create_cube([2,4])

[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]]
